package com.example.simplypresidential.database

import androidx.annotation.DrawableRes
import com.example.simplypresidential.R

data class PresidentData(
    @DrawableRes val image: Int,
    val positionString: String,
    val FirstName: String,
    val LastName: String,
    val StartDate: String,
    val EndDate: String,
)

val PresidentsList = listOf(
    PresidentData(
        R.drawable.pres01,
        "1st",
        "George",
        "Washington",
        "1789",
        "1797"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres03,
        "3rd",
        "Thomas",
        "Jefferson",
        "1801",
        "1809"
    ),
    PresidentData(
        R.drawable.pres04,
        "4th",
        "James",
        "Madison",
        "1809",
        "1817"
    ),
    PresidentData(
        R.drawable.pres05,
        "5th",
        "James",
        "Monroe",
        "1817",
        "1825"
    ),
    PresidentData(
        R.drawable.pres06,
        "6th",
        "John",
        "Adams",
        "1825",
        "1829"
    ),
    PresidentData(
        R.drawable.pres07,
        "7th",
        "Andrew",
        "Jackson",
        "1829",
        "1837"
    ),
    PresidentData(
        R.drawable.pres08,
        "8th",
        "Martin",
        "Van Buren",
        "1841",
        "1841"
    ),
    PresidentData(
        R.drawable.pres09,
        "9th",
        "William",
        "Harrison",
        "1841",
        "1841"
    ),
    PresidentData(
        R.drawable.pres10,
        "10th",
        "John",
        "Tyler",
        "1841",
        "1845"
    ),
    PresidentData(
        R.drawable.pres11,
        "11th",
        "James",
        "Polk",
        "1845",
        "1849"
    ),
    PresidentData(
        R.drawable.pres12,
        "12th",
        "Zachary",
        "Taylor",
        "1850",
        "1853"
    ),
    PresidentData(
        R.drawable.pres13,
        "13th",
        "Millard",
        "Fillmore",
        "1850",
        "1853"
    ),
    PresidentData(
        R.drawable.pres14,
        "14th",
        "Franklin",
        "Pierce",
        "1853",
        "1857"
    ),
    PresidentData(
        R.drawable.pres15,
        "15th",
        "James",
        "Buchanan",
        "1857",
        "1861"
    ),
    PresidentData(
        R.drawable.pres16,
        "16th",
        "Abraham",
        "Lincoln",
        "1861",
        "1865"
    ),
    PresidentData(
        R.drawable.pres17,
        "17th",
        "Andrew",
        "Johnson",
        "1865",
        "1869"
    ),
    PresidentData(
        R.drawable.pres18,
        "18th",
        "Ulysses",
        "Grant",
        "1869",
        "1877"
    ),
    PresidentData(
        R.drawable.pres19,
        "19th",
        "Rutherford",
        "Hayes",
        "1877",
        "1881"
    ),
    PresidentData(
        R.drawable.pres20,
        "20th",
        "James",
        "Garfield",
        "1881",
        "1881"
    ),
    PresidentData(
        R.drawable.pres21,
        "21st",
        "Chester",
        "Authur",
        "1881",
        "1885"
    ),
    PresidentData(
        R.drawable.pres22,
        "22nd",
        "Grover",
        "Cleveland",
        "1885",
        "1889"
    ),
    PresidentData(
        R.drawable.pres23,
        "23rd",
        "Benjamin",
        "Harrison",
        "1889",
        "1893"
    ),
    PresidentData(
        R.drawable.pres24,
        "24th",
        "Grover",
        "Cleveland",
        "1893",
        "1897"
    ),
    PresidentData(
        R.drawable.pres25,
        "25rd",
        "William",
        "McKinley",
        "1897",
        "1901"
    ),
    PresidentData(
        R.drawable.pres26,
        "26th",
        "Theodore",
        "Roosevelt",
        "1901",
        "1909"
    ),
    PresidentData(
        R.drawable.pres27,
        "27th",
        "William",
        "Taft",
        "1909",
        "1913"
    ),
    PresidentData(
        R.drawable.pres28,
        "28th",
        "Woodrow",
        "Wilson",
        "1913",
        "1921"
    ),
    PresidentData(
        R.drawable.pres29,
        "29th",
        "Warren",
        "Harding",
        "1921",
        "1923"
    ),
    PresidentData(
        R.drawable.pres30,
        "30th",
        "Calvin",
        "Coolidge",
        "1923",
        "1929"
    ),
    PresidentData(
        R.drawable.pres31,
        "31st",
        "Herbert",
        "Hoover",
        "1929",
        "1933"
    ),
    PresidentData(
        R.drawable.pres32,
        "32nd",
        "Franklin",
        "Roosevelt",
        "1933",
        "1945"
    ),
    PresidentData(
        R.drawable.pres33,
        "33rd",
        "Harry",
        "Truman",
        "1945",
        "1953"
    ),
    PresidentData(
        R.drawable.pres34,
        "34th",
        "Dwight",
        "Eisenhower",
        "1953",
        "1961"
    ),
    PresidentData(
        R.drawable.pres35,
        "35th",
        "John",
        "Kennedy",
        "1961",
        "1963"
    ),
    PresidentData(
        R.drawable.pres36,
        "36th",
        "Lyndon",
        "Johnson",
        "1963",
        "1969"
    ),
    PresidentData(
        R.drawable.pres37,
        "37th",
        "Richard",
        "Nixon",
        "1969",
        "1974"
    ),
    PresidentData(
        R.drawable.pres38,
        "38th",
        "Gerald",
        "Ford",
        "1974",
        "1977"
    ),
    PresidentData(
        R.drawable.pres39,
        "39th",
        "Jimmy",
        "Carter",
        "1977",
        "1981"
    ),
    PresidentData(
        R.drawable.pres40,
        "40th",
        "Ronald",
        "Reagan",
        "1981",
        "1989"
    ),
    PresidentData(
        R.drawable.pres41,
        "41st",
        "George",
        "Bush",
        "1989",
        "1993"
    ),
    PresidentData(
        R.drawable.pres42,
        "42nd",
        "Bill",
        "Clinton",
        "1993",
        "2001"
    ),
    PresidentData(
        R.drawable.pres43,
        "43rd",
        "George",
        "Bush",
        "2001",
        "2009"
    ),
    PresidentData(
        R.drawable.pres44,
        "44th",
        "Barrack",
        "Obama",
        "2009",
        "2017"
    ),
    PresidentData(
        R.drawable.pres45,
        "45th",
        "Donald",
        "Trump",
        "2017",
        "2021"
    ),
)