package com.example.simplypresidential.database

import androidx.annotation.DrawableRes
import com.example.simplypresidential.R

data class PresidentData(
    @DrawableRes val image: Int,
    val positionString: String,
    val FirstName: String,
    val LastName: String,
    val StartDate: String,
    val EndDate: String,
)

val PresidentsList = listOf(
    PresidentData(
        R.drawable.pres01,
        "1st",
        "George",
        "Washington",
        "1789",
        "1797"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres03,
        "3rd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres01,
        "1st",
        "George",
        "Washington",
        "1789",
        "1797"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres01,
        "1st",
        "George",
        "Washington",
        "1789",
        "1797"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres01,
        "1st",
        "George",
        "Washington",
        "1789",
        "1797"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres01,
        "1st",
        "George",
        "Washington",
        "1789",
        "1797"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres01,
        "1st",
        "George",
        "Washington",
        "1789",
        "1797"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres01,
        "1st",
        "George",
        "Washington",
        "1789",
        "1797"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres01,
        "1st",
        "George",
        "Washington",
        "1789",
        "1797"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
    PresidentData(
        R.drawable.pres02,
        "2nd",
        "John",
        "Adams",
        "1797",
        "1801"
    ),
)